function mixfit4()

global STACK;

nmse(); % Will automatically append normalized MSE metric if

% PASS 1: FIND GOOD INITIAL CONDITIONS BY DECREASING REL ERROR BY 10^-1
fit_boo('StopAtSeconds', 240, ...
        'StepSize', 1.0, ...
        'StepRel', false, ...
        'StepGrowth', 1.3, ...
        'StepShrink', 0.5, ...
        'Elitism', true, ...
        'EliteParams', 5, ...
        'EliteSteps', 5);

% PASS 2: FIT ITERATIVELY (i.e. EACH MODULE CONSIDERED ONE-AT-A-TIME) 
%  Stop when the total relative error is small?
function [o, stepsize] = boosting_as_many_steps_as_there_are_parameters(init_stepsize)    
    if ~exist('init_stepsize', 'var')
        init_stepsize = 1;
    end        
    phi = pack_fittables(STACK);
    [~,o,stepsize] = fit_boo('StopAtStepSize', 10^-7, ...
                             'StepSize', init_stepsize, ...
                             'StopAtStepNumber', length(phi), ...
                             'StepRel', false, ...
                             'Elitism', false, ...
                             'StepGrowth', 1.3); 
end

% Take 10 outer loops
outer_loop_term_fn = create_term_fn('StopAtStepNumber', 10);

fit_iteratively(@boosting_as_many_steps_as_there_are_parameters, ...
                @outer_loop_term_fn);

% PASS 3: FIT ALL MODEL PARAMETERS
fit_boo('StopAtStepSize', 10^-7, ...
        'StepRel', false, ...
        'Elitism', true, ...
        'EliteParams', 5, ...
        'EliteSteps', 5, ...
        'StepGrowth', 1.1, ...
        'StopAtStepNumber', n_params);

end