function qlsq()
fit_lsq('stim', 'respavg', optimset('MaxIter', 500, ...
                                    'MaxFunEvals', 500, ...
                                    'TolFun', 1e-12, 'TolX', 1e-9));
end