function [termcond, n_iters] = fit_fminunc(options)

if nargin < 1
    options = optimset('MaxIter', 9000, ...
                       'MaxFunEvals', 9000, ...
                       'TolFun', 1e-12, ...
                       'TolX', 1e-9);  
end

[termcond, n_iters] = default_fitter_loop('fminunc()', ...
    @(obj_fn, phi_init) fminunc(obj_fn, phi_init, options));    
