function [term_cond, term_score, n_iters, term_step] = fit_fminsearch(options)

if nargin < 1
    options = optimset('MaxIter', 9000, ...
                       'MaxFunEvals', 9000, ...
                       'TolFun', 1e-12, ...
                       'TolX', 1e-9);  
end

[term_cond, term_score, n_iters, term_step] = ...
    default_fitter_loop('fminsearch()', ...
         @(obj_fn, phi_init) fminsearch(obj_fn, phi_init, options));    
    
term_step = nan;