    %% creates scrolling panel
    function buildTestPanel()
        hMainPanel = figure;
        
        pictureFrame = uipanel('Parent', hMainPanel, ...
            'Position', testPanelLoc);

        scrollingPanel = uipanel('Parent', pictureFrame, ...
            'Position', scrollingPanelPos);
        uicontrol('Style', 'slider', ...
            'Parent', pictureFrame, ...
            'Units', 'normalized', ...
            'Value', 1, ...
            'Position', [.95, 0, .05, 1], ...
            'Callback', @scroll);
    end
    %%%% end buildTestPanel

    %% Callback for the scrolling slider %%%%
    function scroll(src, eventdata) %#ok
         movingPanel = findobj(get(src, 'Parent'), ...
             'Tag', 'scrolling_panel');
        val = get(src, 'Value');
        change = [0, val-1, 0, 0];
        set(movingPanel, 'Units', 'normalized', ...
            'Position', scrollingPanelPos-change);
    end
    %%%%