function narf_set_path()
    global NARF_PATH;
    NARF_PATH = '/home/ivar/matlab/narf/';
    addpath([NARF_PATH filesep 'analysis'], ...
            [NARF_PATH filesep 'modules'], ...
            [NARF_PATH filesep 'optimization'], ...
            [NARF_PATH filesep 'utils']);
end