function handles = narf_model_browser(parent_handle)

global STACK XXX META NARF_PATH NARF_SAVED_MODELS_PATH;

if ~exist('parent_handle', 'var')
    parent_handle = figure('Menubar','figure', 'Resize','off', ...
       'Units','pixels', 'Position', [20 50 1200 900]);
end

pos = get(parent_handle, 'Position');
w = pos(3); % Width of the parent panel
h = pos(4); % Height of the parent panel
mw = 250;   % Menu width
ih = 600;   % Image section height
lb = 10;    % Left border spacing
ts = 25;    % Text spacing
tw = 80;    % Text label width
ta = -3;    % Text alignment vertical spacing
vs = 35;    % Vertical spacing between filter lines

% Create a panel inside it which will slide
handles.container_panel = uipanel('Parent',parent_handle, ...
    'Units','pixels', 'Position', [mw 0 w-20 h]);

% Create the scroll bar
handles.container_slider = uicontrol('Parent',parent_handle, ...
    'Style','slider', 'Enable','off', ...
    'Units','pixels', 'Position', [w-20 0 20 ih], ...
    'Min', 0-eps, 'Max', 0, 'Value', 0, ...
    'Callback', @(h,evts,hds) update_panel_positions());

db_results = db_get_models(241, 'por018b-c1');

% Create the data table
handles.db_results = uitable('Parent', parent_handle, ...
        'Enable', 'on',  'Units', 'pixels', 'RowName', [],...
        'ColumnWidth', {50, 40, 100, 300, 50, 50, 70, 150}, ...
        'ColumnName', {'ID', 'Batch', 'CellID', 'ModelName', 'R_test', 'R_fit', 'Sparsity', 'Last Mod.'}, ...
        'Position', [mw ih w-mw h-ih], ...
        'CellEditCallback', @results_data_table_callback);
    
hJScroll = findjobj(handles.db_results); 
hJTable = hJScroll.getViewport.getView; 
hJTable.setNonContiguousCellSelection(false);
hJTable.setColumnSelectionAllowed(false);
hJTable.setRowSelectionAllowed(true);
hJTablecb = handle(hJTable, 'CallbackProperties');
set(hJTablecb, 'MousePressedCallback', {@results_row_select, gcf});
set(hJTablecb, 'KeyPressedCallback', {@results_row_select, gcf});
panax = axes('Units','normal', 'Position', [0 0 1 1],...
    'Parent', handles.container_panel);

    function results_row_select(a,b,c)
        r = a.getSelectedRows();
        %fprintf('New Row Selected: %d\n', r);
        res = db_results(r+1);
        [I,map] = imread(char(res.figurefile),'png');        
        axes(panax);
        imshow(I, map, 'InitialMagnification', 25);
    end

    function results_data_table_callback(a,b,c)
        fprintf('Updating Results Table\n');
        l = length(db_results);
        c = cell(l,8);
        for i = 1:l
            c{i,1} = db_results(i).id;
            c{i,2} = db_results(i).batch;
            c{i,3} = db_results(i).cellid;
            c{i,4} = char(db_results(i).modelname);
            c{i,5} = db_results(i).r_test;
            c{i,6} = db_results(i).r_fit;
            c{i,7} = db_results(i).sparsity;
            c{i,8} = db_results(i).lastmod;
        end
        set(handles.db_results, 'Data', c);
        drawnow;
    end

% Initialize the data table
results_data_table_callback();

% Move all panels around to their proper positions
function update_panel_positions()
    hSld = handles.container_slider;
    hPan = handles.container_panel;
    offset = get(hSld,'Value');
    p = get(hPan, 'Position');
    set(hPan, 'Position', [p(1) -offset p(3) p(4)]);
    top = 1000;
    for yi = 1:N
        p = get(STACK{yi}.gh.fn_panel, 'Position');
        set(STACK{yi}.gh.fn_panel, 'Position', [0 (top-ph*yi-offset) p(3) p(4)]);
    end
    drawnow;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Filter controls
uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'String', 'DB Query Filters', ...
          'Position', [lb h-ts+ta mw-lb ts]);
      
uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Batch #:', ...
          'Position', [lb h-(ts*2)+ta tw-lb ts]);
      
handles.batch = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Batch #', ...
        'Units', 'pixels', 'Position', [tw h-(ts*2) mw-tw ts], ...
        'Callback', @batch_callback);
    
    function batch_callback(a,b,c)
        fprintf('batch_callback');
    end

uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'CellID:', ...
          'Position', [lb h-(ts*3)+ta tw-lb ts]);
      
handles.cellid = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Cellid', ...
        'Units', 'pixels', 'Position', [tw h-(ts*3) mw-tw ts], ...
        'Callback', @cellid_callback);
    
    function cellid_callback(a,b,c)
        fprintf('cellid_callback');
    end

uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Fit Set:', ...
          'Position', [lb h-(ts*4)+ta tw-lb ts]);
      
handles.fit_set = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Fit Set', ...
        'Units', 'pixels', 'Position', [tw h-(ts*4) mw-tw ts], ...
        'Callback', @fit_set_callback);
    
    function fit_set_callback(a,b,c)
        fprintf('fit_set_callback');
    end

uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Token 1:', ...
          'Position', [lb h-(ts*5)+ta tw-lb ts]);
      
handles.token1 = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Filter Token', ...
        'Units', 'pixels', 'Position', [tw h-(ts*5) mw-tw ts], ...
        'Callback', @fit_set_callback);
    
    function model_token1_callback(a,b,c)
        fprintf('model_token1_callback');
    end
uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Token 2:', ...
          'Position', [lb h-(ts*6)+ta tw-lb ts]);
      
handles.token2 = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Filter Token', ...
        'Units', 'pixels', 'Position', [tw h-(ts*6) mw-tw ts], ...
        'Callback', @fit_set_callback);
    
    function model_token2_callback(a,b,c)
        fprintf('model_token2_callback');
    end
                
uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Token 3:', ...
          'Position', [lb h-(ts*7)+ta tw-lb ts]);
      
handles.token3 = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Filter Token', ...
        'Units', 'pixels', 'Position', [tw h-(ts*7) mw-tw ts], ...
        'Callback', @fit_set_callback);
    
    function model_token3_callback(a,b,c)
        fprintf('model_token3_callback');
    end
                
uicontrol('Parent', parent_handle, 'Style', 'text', 'Units', 'pixels',...
          'HorizontalAlignment', 'left', ...
          'String', 'Token 4:', ...
          'Position', [lb h-(ts*8)+ta tw-lb ts]);
      
handles.token4 = uicontrol('Parent', parent_handle, ...
        'Style', 'popupmenu', 'Enable', 'on', ...
        'String', 'Select Filter Token', ...
        'Units', 'pixels', 'Position', [tw h-(ts*8) mw-tw ts], ...
        'Callback', @fit_set_callback);
    
    function model_token4_callback(a,b,c)
        fprintf('model_token4_callback');
    end

end