function abc ()

global MODULES;

append_module(MODULES.state_space_diffeq.mdl(...
                  struct('fit_fields', {{'A', 'C', 'delay_B', 'delay_B_amount'}}, ...
                         'A', [0.5 0.5; 0.5 0.5], ...
                         'B', [0 0; 0 0], ...
                         'C', [0.5 0.5], ...
                         'D', [0 0], ...
                         'delay_B', [0.5 0.5; 0.5 0.5], ...
                         'delay_B_amount' , 20)));
              
end