function abcdv2()

global MODULES;

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

append_module(MODULES.state_space_diffeq.mdl(...
                  struct('fit_fields', {{'A', 'B', 'C', 'D', 'delay_B', 'delay_B_amount', 'y_offset'}}, ...
                         'A', [0.0266    2.1573; 21.3997 -127.8786], ...
                         'B', [-2.1; -10.6], ...
                         'C', [0.5 -1.2], ...
                         'D', [0.05],...
                         'delay_B', [34.5353; 56.7038], ...
                         'delay_B_amount' , 0.0335, ...
                         'y_offset', 1)));
              
end