function fit09r()

global STACK;

semse();

phi = pack_fittables(STACK)'; 

opts = saoptimset('MaxIter', length(phi) * 200, ...
                  'MaxFunEvals', length(phi) * 200, ...
                  'InitialTemperature', 0.5, ...
                  'AnnealingFcn', @annealingboltz, ...
                  'TemperatureFcn', @temperatureboltz, ...
                  'Display', 'diagnose', ...
                  'TolFun', 0.01);
fit_anneal(opts);

end
