function apgt01 ()

global MODULES STACK XXX META;

append_module(MODULES.pz_wavelet.mdl(...
                struct('fit_fields', {{'center_freq', 'Q_factor', 'N_order', ...
                                       'gain', 'delayms', 'y_offset'}}, ...
                       'center_freq', 2.0, ...
                       'N_order', 3, ...
                       'Q_factor', 3, ... 
                       'input', 'stim', ...
                       'output', 'stim')));  

append_module(MODULES.downsample_signal.mdl(...
                struct('input', 'stim', ...
                       'input_freq', 100000, ...
                       'output', 'stim', ...
                       'output_freq', 1000, ...
                       'output_time', 'stim_time')));            

%narf_modelpane;
%keyboard;
%fit04a();
nmse();
[a,b,c,d] = fit_scaat('InitStepSize', 100.0, 'StopAtAbsScoreDelta', 10^-1);
[a,b,c,d] = fit_scaat('InitStepSize', 100.0, 'StopAtAbsScoreDelta', 10^-2);
[a,b,c,d] = fit_scaat('InitStepSize', 100.0, 'StopAtAbsScoreDelta', 10^-3);
[a,b,c,d] = fit_scaat('InitStepSize', 100.0, 'StopAtAbsScoreDelta', 10^-4);
% fit05;

end