function boo00()
mse();

% Timed for two minutes, with conservative parameters
fit_boo(struct('StopAtSeconds', 240, ...
               'StopAtStepNumber', 10000, ...
               'StopAtStepSize', 10^-12, ...
               'StopAtRelScoreDelta', 10^-12, ...
               'StopAtAbsScoreDelta', 10^-12, ...
               'StepSize', 1.0, ...
               'StepRel', true, ...
               'StepRelRecalcEvery', 1, ...
               'StepRelMin', 10^-3, ...
               'StepRelMax', 10^3, ...
               'StepGrowth', 1.0, ...
               'StepShrink', 0.5, ...
               'Elitism', false, ...
               'EliteParams', 10, ...
               'EliteSteps', 1));