function boo12()
% Only append MSE module if needed
mods = find_modules(STACK, 'mean_squared_error', true);
if isempty(mods)
    mse();    
end

% PASS 1: FIT ALL MODEL PARAMETERS
phi_init = pack_fittables(STACK);
n_params = length(phi_init);
fit_boo(struct('StopAtStepSize', 10^-7, ...
               'StopAtTime', 240, ...
               'StepRel', true, ...
               'StepRelMin', 10^0, ...
               'StepRelMax', 10^1, ...
               'StepRelRecalcEvery', 5, ...
               'StopAtRelScoreDelta', 10^-5, ...
               'StopAtStepNumber', n_params, ...
               'StepSize', 1.0, ...
               'StepGrowth', 1.0, ...
               'StepShrink', 0.5, ...
               'Elitism', false, ...
               'EliteParams', 5, ...
               'EliteSteps', 10));