function dep1pc()
% single depression synapse, independent per stimulus channel, with
% normal intial conditions.

global MODULES XXX;

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

sf=XXX{end}.training_set{1};
chan_count=size(XXX{end}.dat.(sf).stim,3);
init_str=repmat(5,[1 chan_count]);
init_tau=repmat(20,[1 chan_count]);
init_offset=zeros(1,chan_count);

% not using crosstalk
append_module(MODULES.depression_filter_bank.mdl(...
                    struct('strength', init_str, ...
                           'tau',      init_tau, ...
                           'offset_in',init_offset,...
                           'tau_norm',  100,...
                           'per_channel', 1, ...
                           'crosstalk', 0, ...
                           'fit_fields', {{'strength', 'tau', 'offset_in'}}, ...
                           'fit_constraints', {{struct( ...
                                  'var', 'strength', ...
                                  'lower', -100*ones(1,chan_count), ...
                                  'upper', 100*ones(1,chan_count)), ...
                                  struct( ...
                                  'var', 'tau', ...
                                  'lower', -200*ones(1,chan_count), ...
                                  'upper', 200*ones(1,chan_count)), ...
                                  struct( ...
                                  'var', 'offset_in', ...
                                  'lower', -50*ones(1,chan_count), ...
                                  'upper', 50*ones(1,chan_count))}} ...
              )));
