function dep2n()

global MODULES;

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

append_module(MODULES.depression_filter_bank.mdl(...
                    struct('strength', [0,  0.2    0.2], ...
                           'tau',      [0,  50,    200], ...
                           'num_channels', 3)));

append_module(MODULES.normalize_channels.mdl(struct('force_positive', false)));

append_module(MODULES.fir_filter.mdl(struct('num_coefs', 10, ...
                                     'fit_fields', {{'coefs','baseline'}},...
                                     'output','stim1')));

append_module(MODULES.fir_filter.mdl(struct('num_coefs', 10, ...
                                     'fit_fields', {{'coefs','baseline'}},...
                                     'output','stim2')));

