function env300()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 300, ...
                                  'raw_stim_fs', 300,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'envelope'))); 
                              
