function env500()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 500, ...
                                  'raw_stim_fs', 500,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'envelope'))); 
                              
