function fir15pc()

global MODULES XXX;

fir_num_coefs=15;

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

meanresp = nanmean(flatten_field(XXX{end}.dat,XXX{end}.training_set,'respavg'));
append_module(MODULES.fir_filter.mdl(struct('num_coefs', fir_num_coefs, ...
                                'baseline',meanresp,...
                                'sum_channels', false, ...
                                'fit_fields', {{'coefs','baseline'}}, ...
                                 'fit_constraints', {{struct( ...
                                                       'var', 'coefs', ...
                                                       'lower', -50, ...
                                                       'upper', 50), ...
                                                     struct( ...
                                                       'var', 'baseline', ...
                                                       'lower', -50, ...
                                                       'upper', 50)}} ...
                                )));

fitSubstack([],10^-2);
