function gt24ch500()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 500, ...
                                  'raw_stim_fs', 500,...
                                  'stimulus_channel_count', 24, ...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'gamma'))); 
