function inex()

global MODULES;

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

append_module(MODULES.fir_filter.mdl(struct('fit_fields', {{'coefs'}}, ...
                                            'num_coefs', 12, ...
                                            'output', 'inhib')));
                                        
append_module(MODULES.fir_filter.mdl(struct('fit_fields', {{'coefs'}}, ...
                                                 'num_coefs', 12, ...
                                                 'output', 'excit')));

append_module(MODULES.nonlinearity.mdl(struct('fit_fields', {{'phi'}}, ...
                                                   'input_stim', 'inhib', ...
                                                   'output', 'inhib', ...
                                                   'phi', [0], ...
                                                   'nlfn', @(phi, z) - nl_zerothresh(phi, z))));
                                               

append_module(MODULES.nonlinearity.mdl(struct('fit_fields', {{'phi'}}, ...
                                              'input_stim', 'excit', ...
                                              'output', 'excit', ...
                                              'phi', [0], ...
                                              'nlfn', @nl_zerothresh)));

append_module(MODULES.sum_fields.mdl(struct('inputs', {{'inhib', 'excit'}}, ...
                                                 'output', 'stim')));

append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));


