function isi200v2()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 10000, ...
                                  'raw_stim_fs', 200,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'envelope'))); 

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 200, ...
                                  'raw_stim_fs', 200,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'envelope', ...
                                  'output_stim', 'stim200', ...
                                  'output_stim_time', 'stim200time', ...
                                  'output_resp', 'resp200', ...
                                  'output_resp_time', 'resp200time', ...
                                  'output_respavg', 'respavg'))); 

append_module(MODULES.inter_spike_intervals); 
