function isi200()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 10000, ...
                                  'raw_stim_fs', 200,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'envelope'))); 

append_module(MODULES.inter_spike_intervals); 

append_module(MODULES.downsample_signal.mdl(...
                    struct('input_freq', 10000, ...
                           'input', 'respavg', ...
                           'input_time', 'resp_time', ...
                           'output_freq', 200, ...
                           'output', 'respavg', ...
                           'output_time', 'respavg_time'))); 
