function lindeberg1015()
% March 2014 - lienard
% modified from 'fir.m'

% Linderberg's time-causal kernels of order (dx=1,dt=0)

global MODULES XXX;

fir_num_coefs=15; % was 12 previously (JL)
stop_exp=2.0;


append_module(MODULES.normalize_channels.mdl(struct('force_positive', true)));

meanresp = nanmean(flatten_field(XXX{end}.dat,XXX{end}.training_set,'respavg'));
append_module(MODULES.lindeberg_filter.mdl(struct('num_coefs', fir_num_coefs, ...
                                'order_x',1,...
                                'order_t',0,...
                                'baseline',meanresp,...
                                'fit_fields', {{'lincoefs','baseline'}}, ...
              'fit_constraints', {{struct( ...
                                         'var', 'lincoefs', ...
                                         'lower', [0  0  0 0.5 -2 -10], ...
                                         'upper', [18 15 18  10  2  10 ]), ...
                                   struct( ...
                                         'var', 'baseline', ...
                                         'lower', -50, ...
                                         'upper', 50)}} ...
             )));
%                                 'fit_fields', {{'lincoefs'}})));

fitSubstack([],10^-(stop_exp));
