function linspec0()
% Weight all input channels, producing 1 output channel
% Works on 'stim' by default. 
global MODULES;

append_module(MODULES.lindeberg_spectral.mdl(...
       struct('order', 0, ...
              'fit_fields', {{'bf', 's', 'add_factor', 'norm_factor'}}, ...
              'fit_constraints', {{struct( ...
                                         'var', 'bf', ...
                                         'lower', 0, ...
                                         'upper', 1), ...
                                   struct( ...
                                         'var', 's', ...
                                         'lower', 0, ...
                                         'upper', 1), ...
                                   struct( ...
                                         'var', 'add_factor', ...
                                         'lower', -50, ...
                                         'upper', 50), ...
                                   struct( ...
                                         'var', 'norm_factor', ...
                                         'lower', -50, ...
                                         'upper', 50)}} ...
             )));
