function mixfit4()

global STACK;

% Only append MSE module if needed
mods = find_modules(STACK, 'mean_squared_error', true);
if isempty(mods)
    mse();    
end

% PASS 1: FIT ALL MODEL PARAMETERS
phi_init = pack_fittables(STACK);
n_params = length(phi_init);
fit_boo(struct('StopAtStepSize', 10^-7, ...
               'StepRel', true, ...
               'StepRelMin', 10^0, ...
               'StepRelMax', 10^1, ...
               'StepRelRecalcEvery', 5, ...
               'StopAtRelScoreDelta', 10^-5, ...
               'StopAtStepNumber', n_params, ...
               'StepSize', 1.0, ...
               'StepGrowth', 1.0, ...
               'StepShrink', 0.5, ...
               'Elitism', false, ...
               'EliteParams', 5, ...
               'EliteSteps', 10));

% PASS 2: FIT ITERATIVELY (i.e. EACH MODULE CONSIDERED ONE-AT-A-TIME)
function boosting_as_many_steps_as_there_are_parameters()    
    phi = pack_fittables(STACK);
    @() fit_boo(struct('StopAtStepSize', 10^-7, ...
                       'StepRel', true, ...
                       'StopAtStepNumber', length(phi)));                      
end
max_loops = 13;
fit_iteratively(boosting_as_many_steps_as_there_are_parameters, max_loops);

% PASS 3: FIT ALL MODEL PARAMETERS USING EFFECT-SCALED STEPSIZES     
fit_boo(struct('StopAtStepSize', 10^-7, ...
               'StepRel', true, ...
               'StopAtRelScoreDelta', 10^-5, ...
               'StopAtStepNumber', n_params));
           
end