function mixfit5()

global STACK;

% Only append MSE module if needed
mods = find_modules(STACK, 'mean_squared_error', true);
if isempty(mods)
    mse();    
end

% PASS 1: Fit model parameters for 5 minutes to find ok initial conditions
phi_init = pack_fittables(STACK);
n_params = length(phi_init);
fit_boo(struct('StopAtSeconds', 300, ...
               'StopAtStepNumber', 10000, ...
               'StopAtStepSize', 10^-12, ...
               'StopAtRelScoreDelta', 10^-12, ...
               'StopAtAbsScoreDelta', 10^-12, ...
               'StepSize', 1.0, ...
               'StepRel', false, ...
               'StepRelRecalcEvery', 1, ...
               'StepRelMin', 10^-3, ...
               'StepRelMax', 10^3, ...
               'StepGrowth', 1.3, ...
               'StepShrink', 0.5, ...
               'Elitism', true, ...
               'EliteParams', 5, ...
               'EliteSteps', 5));

% PASS 2: Use the mighty SCAAT fitter now that initial conditions are good
fit_scaat();

end