function npg()

global MODULES;

% default inputs are already stim1, stim2
% default output already stim
append_module(MODULES.nonparm_gain.mdl(struct('bincount', 5,...
   'gain',[1 1 1 1 1].*100,...
   'offset',[0 0 0 0 0],...
   'fit_fields', {{'gain','offset'}},...
   'smoothwindow',0)));
