function sig5PL()

global MODULES XXX;

ff=XXX{end}.training_set{1};
maxresp = max(XXX{end}.dat.(ff).stim(:));
minresp = min(XXX{end}.dat.(ff).stim(:));

append_module(MODULES.nonlinearity.mdl(...
    struct('fit_fields', {{'phi'}}, ...
            'fit_constraints', {{struct( ...
                                     'var', 'phi', ...
                                     'lower', [0     0   0   0 -100], ...
                                     'upper', [100 100 200 100 100], ...
                                     'fitter', 'custom')}}, ...
           'phi', [minresp minresp+maxresp 1 3 1], ...
           'nlfn', @nl_sig_5PL)));

fitSubstack();