function syn01 ()

global MODULES STACK XXX META;

append_module(MODULES.pz_synapse.mdl(...
                struct('fit_fields', {{'poles', 'zeros', 'gain', 'delayms', ...
                                       'prephi', 'postphi', 'y_offset'}}, ...
                       'poles', [-80], ...
                       'zeros', [], ...
                       'gain', 10, ...
                       'prefn', @nl_zerothresh, ...
                       'prephi', [0], ...
                       'postfn', @nl_zerothresh, ...
                       'postphi', [0], ...
                       'input', 'stim', ...
                       'output', 'stim1')));                                      
                 
append_module(MODULES.sum_fields.mdl(struct('inputs', {{'stim1'}})));
fit04a(); pop_module(); pop_module();
STACK{end}{1} = rmfield(STACK{end}{1}, 'fit_fields');

append_module(MODULES.pz_synapse.mdl(...
                struct('fit_fields', {{'poles', 'zeros', 'gain', 'delayms', ...
                                       'prephi', 'postphi', 'y_offset'}}, ...
                       'poles', [-50], ...
                       'zeros', [], ...
                       'gain', -5, ...
                       'prefn', @nl_zerothresh, ...
                       'prephi', [0], ...
                       'postfn', @nl_zerothresh, ...
                       'postphi', [0], ...
                       'input', 'stim', ...
                       'output', 'stim2')));     

append_module(MODULES.sum_fields.mdl(struct('inputs', {{'stim1', 'stim2'}})));
fit04a(); pop_module(); pop_module();
STACK{end}{1} = rmfield(STACK{end}{1}, 'fit_fields');

append_module(MODULES.pz_synapse.mdl(...
                struct('fit_fields', {{'poles', 'zeros', 'gain', 'delayms', ...
                                       'prephi', 'postphi', 'y_offset'}}, ...
                       'poles', [-2], ...
                       'zeros', [], ...
                       'gain', -10, ...
                       'prefn', @nl_zerothresh, ...
                       'prephi', [0], ...
                       'postfn', @nl_zerothresh, ...
                       'postphi', [0], ...
                       'input', 'stim', ...
                       'output', 'stim3'))); 

append_module(MODULES.sum_fields.mdl(struct('inputs', {{'stim1', 'stim2', 'stim3'}})));
fit04a(); pop_module(); 
STACK{end}{1} = rmfield(STACK{end}{1}, 'fit_fields');

siglog();
fit04a(); pop_module();

% Now go through and re-fit everything a second time
for ii = 1:length(STACK)
    if strcmp(STACK{ii}{1}.name, 'pz_synapse')
        STACK{ii}{1}.fit_fields = {'poles', 'zeros', 'gain', 'delayms', ...
                                   'prephi', 'postphi'};
    end
end

fit04a();



end