function wav100k()

global MODULES;

append_module(MODULES.load_stim_resps_from_baphy.mdl(...
                           struct('raw_resp_fs', 1000, ...
                                  'raw_stim_fs', 100000,...
                                  'include_prestim', true, ...
                                  'stimulus_format', 'wav'))); 
                              
