function wcg01()
% Weight channels, using a gaussian parameterization
% Works on 'stim' by default. 
global MODULES STACK XXX;

append_module(MODULES.weight_channels.mdl(...
       struct('phifn', @wc_gaussian, ...
              'phi', [2 5], ...
              'fit_fields', {{'phi'}})));
