function wcgd02()
% Weight channels, using a gaussian parameterization
% Works on 'stim' by default. 
global MODULES;

append_module(MODULES.weight_channels.mdl(...
       struct('phifn', @wc_gaussian_differences, ...
              'phi', [7 3 0.5 1.6; 3 3 0.5 1.6], ...
              'y_offset', [0; 0], ...
              'fit_fields', {{'phi'}})));
