function wcgd03()
% Weight channels, using a gaussian parameterization
% Works on 'stim' by default. 
global MODULES;

append_module(MODULES.weight_channels.mdl(...
       struct('phifn', @wc_gaussian_differences, ...
              'phi', [2 5 0.0 1.6; 3 5 0.0 1.6; 4 5 0.0 1.6], ...
              'y_offset', [0; 0; 0], ...
              'fit_fields', {{'phi'}})));
