function wcgr02()
% Weight channels, using a gaussian parameterization, square-rooted
% Works on 'stim' by default. 
global MODULES STACK XXX;

append_module(MODULES.weight_channels.mdl(...
       struct('phifn', @wc_gaussian_root, ...
              'phi', [2 5 2; 3 5 2], ...
              'y_offset', [0; 0], ...
              'fit_fields', {{'phi'}})));
