function wcm02()
% Weight channels, using a morlet wavelet
% Works on 'stim' by default. 
global MODULES;

append_module(MODULES.weight_channels.mdl(...
       struct('phifn', @wc_morlet, ...
              'phi', [7 5 0.4; 1 5 0.4], ...
              'y_offset', [0; 0], ...
              'fit_fields', {{'phi'}})));
