function wenv50()

global MODULES;
global ANESTHETIZED_MOUSE
ANESTHETIZED_MOUSE=1;

append_module(MODULES.load_stim_resps_wehr.mdl(...
                           struct('raw_resp_fs', 50, ...
                                  'raw_stim_fs', 50,...
                                  'include_prestim', false, ...
                                  'stimulus_format', 'envelope'))); 

