
dbopen;
sql=['select sCellFile.* from sCellFile inner join gCellMaster on' ...
     ' sCellFile.masterid=gCellMaster.id WHERE gCellMaster.well=13' ...
     ' ORDER BY sCellFile.cellid,sCellFile.stimfile'];
filedata=mysql(sql);

for ii=1:length(filedata),
   load([filedata(ii).path,filedata(ii).respfile],filedata(ii).respvarname);
   eval(['p=',filedata(ii).respvarname,';']);
   resplen=sum(~isnan(p));
   fprintf('%-40s resplen=%d\n',filedata(ii).respfile,resplen);
   sql=['update sCellFile set resplen=',num2str(resplen),...
        ' where id=',num2str(filedata(ii).id)];
   mysql(sql);
end

return


dbopen;

sql=['SELECT * FROM tCellFile'];
cellfiledata=mysql(sql);

for ii=1:length(cellfiledata),
   rawid=cellfiledata(ii).rawid;
   sql=['SELECT * FROM gDataRaw WHERE id=',num2str(rawid)];
   rawdata=mysql(sql);
   
   sql=['SELECT * FROM sCellFile WHERE rawid=',num2str(rawid)];
   newfiledata=mysql(sql);
   
   if length(rawdata)==0,
      fprintf('skpping absent gDataRaw entry for %s\n',...
              cellfiledata(ii).respfile);
   elseif length(rawdata)~=1,
      disp('error! rawdata<>1!');
      keyboard;
   elseif strcmp(rawdata.cellid,''),
      fprintf('updating gDataRaw entry for %s\n',...
              cellfiledata(ii).respfile);
      sql=['UPDATE gDataRaw SET',...
           ' cellid="',cellfiledata(ii).cellid,'",',...
           ' resppath="',cellfiledata(ii).path,'",',...
           ' stimfile="',cellfiledata(ii).stimfile,'",',...
           ' respfile="",',...
           ' matlabfile="',cellfiledata(ii).respfile,'",',...
           ' stimpath="',cellfiledata(ii).path,'",',...
           ' comments="imported from tCellFile"',...
           ' WHERE id=',num2str(rawid)];
      mysql(sql);
   end
   
   % add sCellFile entry for fixation data if it doesn't exist yet
   if length(rawdata)>0 & ismember(rawdata.runclassid,[0 1 2 5]) & length(newfiledata)==0,
      fprintf('adding sCellFile entry for %s\n',...
              cellfiledata(ii).respfile);
      sqlinsert('sCellFile',...
                'cellid',cellfiledata(ii).cellid,...
                'masterid',rawdata.masterid,...
                'rawid',rawid,...
                'celldataid',cellfiledata(ii).id,...
                'runclassid',rawdata.runclassid,...
                'path',cellfiledata(ii).path,...
                'resplen',cellfiledata(ii).resplen,...
                'repcount',cellfiledata(ii).repcount,...
                'respfile',cellfiledata(ii).respfile,...
                'respfiletype',cellfiledata(ii).respfiletype,...
                'nosync',cellfiledata(ii).nosync,...
                'respvarname',cellfiledata(ii).respvarname,...
                'respfilefmt',cellfiledata(ii).respfilefmt,...
                'respfmtcode',cellfiledata(ii).respfmtcode,...
                'stimfile',cellfiledata(ii).stimfile,...
                'stimfiletype',cellfiledata(ii).stimfiletype,...
                'stimiconside',num2str(cellfiledata(ii).stimiconside),...
                'stimfilecrf',cellfiledata(ii).stimfilecrf,...
                'stimwindowsize',cellfiledata(ii).stimwindowpix,...
                'stimfilefmt',cellfiledata(ii).stimfilefmt,...
                'stimfmtcode',cellfiledata(ii).stimfmtcode,...
                'addedby','david',...
                'info','dbcrap.m - from tCellFile');
                
      
   end
end










return


sql=['SELECT * FROM gCellMaster WHERE penid=0 order by cellid'];
celldata=mysql(sql);

for ii=1:length(celldata),
   if isempty(celldata(ii).penname),
      if isnumeric(celldata(ii).cellid(end)),
         celldata(ii).penname=celldata(ii).cellid;
      else
         celldata(ii).penname=celldata(ii).cellid(1:(end-1));
      end
   end
   
   sql=['SELECT * FROM gPenetration where penname="', ...
	celldata(ii).penname,'"'];
   pendata=mysql(sql);
   if length(pendata)>0,
      penid=pendata(1).id;
      fprintf('penname exists with id=%d\n',penid);
   else
      % create a new entry in gPenetration
      [aff,penid]=sqlinsert('gPenetration',...
			    'penname',celldata(ii).penname,...
			    'well',celldata(ii).well,...
			    'animal',celldata(ii).animal,...
			    'addedby','david',...
			    'info','dbcrap.m');
   end
   
   sql=['UPDATE gCellMaster SET penid=',num2str(penid),',',...
        ' penname="',celldata(ii).penname,'"',...
	' WHERE id=',num2str(celldata(ii).id)];
   mysql(sql);
end
