
animal='venus';
sql=['SELECT gDataRaw.* FROM gDataRaw,gCellMaster,gPenetration',...
     ' WHERE gCellMaster.penid=gPenetration.id',...
     ' AND gDataRaw.masterid=gCellMaster.id',...
     ' AND (isnull(matlabfile) OR matlabfile="")',...
     ' AND gPenetration.animal="',animal,'"',...
     ' AND not(gDataRaw.training)'];
rawdata=mysql(sql);

schan={'a','b','c','d','e','f','g','h'};

for ii=1:length(rawdata),
   [pp,bb,ee]=fileparts(rawdata(ii).parmfile);
   
   mattest=[rawdata(ii).resppath 'sorted/' bb '.spk.mat'];
   
   if exist(mattest,'file'),
      s=load(mattest);
      
      % figure out some basic info for db linking
      siteid=rawdata(ii).cellid;
      masterid=rawdata(ii).masterid;
      rawid=rawdata(ii).id;
      runclassid=rawdata(ii).runclassid;
      parmfile=rawdata(ii).parmfile;
      parmpath=rawdata(ii).resppath;
      
      sql=['SELECT * FROM gCellMaster WHERE id=',num2str(masterid)];
      masterdata=mysql(sql);
      penid=masterdata.penid;
      areas=strsep(masterdata.area,',');
      if isempty(areas),
         % possible kludge
         %areas={'A1','A1','A1','A1','A1','A1','A1','A1'};
      end
      
      for cc=1:length(s.sortinfo),
         if length(s.sortinfo{cc})>0,
            ncells=s.sortinfo{cc}{1}(1).Ncl;
         else
            ncells=0;
         end
         for uu=1:ncells,
            cellid=[siteid '-' schan{cc} num2str(uu)];
            spikecount=size(s.sortinfo{cc}{1}(uu).unitSpikes,2)
            
            
            sql=['SELECT * FROM gSingleCell WHERE cellid="',cellid,'"'];
            singledata=mysql(sql);
            
            if isempty(singledata) && cc==1,
               cellid=[siteid '-' num2str(uu)];
               
               sql=['SELECT * FROM gSingleCell WHERE cellid="',cellid,'"'];
               singledata=mysql(sql);
            end
            
            if isempty(singledata),
               [aff,singleid]=sqlinsert('gSingleCell',...
                                        'siteid',siteid,...
                                        'cellid',cellid,...
                                        'masterid',masterid,...
                                        'penid',penid,...
                                        'channel',schan{cc},...
                                        'unit',uu,...
                                        'channum',cc,...
                                        'area',areas{cc},...
                                        'addedby','david',...
                                        'info','lookforjustin.m');
               fprintf('added gSingleCell entry %d\n',singleid);
            else
               singleid=singledata(1).id;
            end
            
            sql=['SELECT * FROM gSingleRaw WHERE singleid=',num2str(singleid),...
                 ' AND rawid=',num2str(rawid)];
            singlerawdata=mysql(sql);
            if isempty(singlerawdata),
               [aff,singlerawid]=sqlinsert('gSingleRaw',...
                                           'cellid',cellid,...
                                           'masterid',masterid,...
                                           'singleid',singleid,...
                                           'penid',penid,...
                                           'rawid',rawid,...
                                           'channel','a',...
                                           'unit',uu,...
                                           'channum',1,...
                                           'addedby','david',...
                                           'info','import_sorted_justin.m');
               fprintf('added gSingleRaw entry %d\n',singlerawid);
            else
               singlerawid=singlerawdata.id;
            end
            
            sql=['SELECT * FROM sCellFile WHERE singleid=',num2str(singleid),...
                 ' AND rawid=',num2str(rawid)];
            cellfiledata=mysql(sql);
            if isempty(cellfiledata),
               [aff,cellfileid]=...
                   sqlinsert('sCellFile',...
                             'cellid',cellid,...
                             'masterid',masterid,...
                             'singleid',singleid,...
                             'singlerawid',singlerawid,...
                             'rawid',rawid,...
                             'unit',uu,...
                             'channum',cc,...
                             'runclassid',runclassid,...
                             'area','A1',...
                             'path',[fileparts(mattest) filesep],...
                             'resplen',sum(s.npoint),...
                             'repcount',s.nsweep,...
                             'respfile',basename(mattest),...
                             'respvarname','sortinfo',...
                             'respfiletype',uu,...
                             'respfmtcode',1,...
                             'respfilefmt','justin',...
                             'stimfile',parmfile,...
                             'stimfilecrf',0,...
                             'stimfilefmt','par',...
                             'stimfmtcode',1,...
                             'stimspeedid',3,...
                             'stimsnr',1000,...
                             'stimpath',parmpath,...
                             'spikes',spikecount,...
                             'addedby','david',...
                             'info','import_sorted_justin.m');
               fprintf('added sCellFile entry %d\n',cellfileid);
            else
               cellfileid=cellfiledata.id;
            end
             
            
            
         end
      end
      
      sql=['UPDATE gDataRaw set matlabfile="',mattest,'"',...
           ' WHERE id=',num2str(rawid)];
      mysql(sql);
      
      fprintf('done with %s\n',parmfile);
      
   end
end
