

dbopen('localhost','david','nine1997','npc');
mysql('use npc');

% get cell data in the correct folders
% figure out all the filenames and associated data
% enter dataset, datafiles in db
% generate mfile with specs
% figure out what actually needs to get distributed in download.

distpath='/home2/data/npc/data/03_v1_nis/';
datapath='/home2/data/npc/data/03_v1_nis/v1_nis_data/';
dataname='V1 Natural Image Sequences';
area='V1';
system='visual cortex';

cd(datapath);
cellinfo;

infofile='cellinfo';
codefile='';
stimloadcmd='loadimfile';
resploadcmd='load';
comments=['Random natural images presented at 60Hz in to V1 neurons' ...
          ' during fixation.'];
addedby='david';

stimHz=60;
respHz=60;
binsize=17;
dsid=3;

mysql(['delete from nDataFile where datasetid=',num2str(dsid)]);
mysql(['delete from nDataSet where id=',num2str(dsid)]);
mysql(['delete from nFiles where datasetid=2',num2str(dsid)]);


[add,dsid]=sqlinsert('nDataSet',...
                     'id',dsid,...
                     'dataname',dataname,...
                     'system',system,...
                     'path',datapath,...
                     'readmefile','README',...
                     'infofile',infofile,...
                     'stimloadcmd',stimloadcmd,...
                     'resploadcmd',resploadcmd,...
                     'comments',comments,...
                     'addedby',addedby,...
                     'addeddate',datestr(now,31),...
                     'info','npc_adddata');
fprintf('added dataset %s datasetid %d\n',dataname,dsid);

for ii=1:length(celldata),
   valrespfile=sprintf('../val_data/%s_val.mat',celldata(ii).cellid);
   
   [add,dfid]=sqlinsert('nDataFile',...
                        'cellid',celldata(ii).cellid,...
                        'datasetid',dsid,...
                        'area',area,...
                        'system',system,...
                        'path',datapath,...
                        'respfile',celldata(ii).datafile,...
                        'stimfile',celldata(ii).datafile,...
                        'valrespfile',valrespfile,...
                        'valstimfile',celldata(ii).datafile,...
                        'comments','',...
                        'binsize',binsize,...
                        'stimHz',stimHz,...
                        'respHz',respHz,...
                        'addedby',addedby,...
                        'addeddate',datestr(now,31),...
                        'info','npc_adddata2');
   fprintf('added cell %s datafileid %d\n',celldata(ii).cellid,dfid);
end

filename='v1_nisdata_full.tgz';
comment='V1 Natural Image Sequence data. Full-size files with complete stimuli.';
[add,fileid]=sqlinsert('nFiles',...
                       'datasetid',dsid,...
                       'path',datapath,...
                       'filename',filename,...
                       'comment',comment,...
                       'contenttype','application/octet-stream',...
                       'category','dataset',...
                       'seclevel',2,...
                       'addedby',addedby,...
                       'addeddate',datestr(now,31),...
                       'info','npc_adddata');
fprintf('added file %s id %d\n',filename,fileid);

filename='v1_nisdata_small.tgz';
comment=['V1 Natural Image Sequence data. Downsampled (16x16 pixel)' ...
         ' stimuli only.'];
[add,fileid]=sqlinsert('nFiles',...
                       'datasetid',dsid,...
                       'path',distpath,...
                       'filename',filename,...
                       'comment',comment,...
                       'contenttype','application/octet-stream',...
                       'category','dataset',...
                       'seclevel',2,...
                       'addedby',addedby,...
                       'addeddate',datestr(now,31),...
                       'info','npc_adddata');
fprintf('added file %s id %d\n',filename,fileid);
 
filename='README';
comment=['V1 Natural Image Sequence data general information'];
[add,fileid]=sqlinsert('nFiles',...
                       'datasetid',dsid,...
                       'path',distpath,...
                       'filename',filename,...
                       'contenttype','text/plain',...
                       'comment',comment,...
                       'category','dataset',...
                       'seclevel',2,...
                       'addedby',addedby,...
                       'addeddate',datestr(now,31),...
                       'info','npc_adddata');
fprintf('added file %s id %d\n',filename,fileid);
 
