

dbopen('bhangra','david','nine1997','npc');
mysql('use npc');

% get cell data in the correct folders
% figure out all the filenames and associated data
% enter dataset, datafiles in db
% generate mfile with specs
% figure out what actually needs to get distributed in download.

datapath='/home2/data/npc/data/02_fieldL_song/fieldL_data/';
dataname='Field L Birdsong';
area='Field L';
system='birdsong';

cd(datapath);
cellinfo;

infofile='cellinfo';
codefile='';
stimloadcmd='load';
resploadcmd='load';
comments='Field L data from Frederic Theunissen';
addedby='junli';

stimHz=32000;
respHz=1000;
binsize=1;
dsid=2;

mysql(['delete from nDataFile where datasetid=',num2str(dsid)]);
mysql(['delete from nDataSet where id=',num2str(dsid)]);
mysql(['delete from nFiles where datasetid=2',num2str(dsid)]);


[add,dsid]=sqlinsert('nDataSet',...
                     'id',dsid,...
                     'dataname',dataname,...
                     'system',system,...
                     'path',datapath,...
                     'readmefile','README',...
                     'infofile',infofile,...
                     'stimloadcmd',stimloadcmd,...
                     'resploadcmd',resploadcmd,...
                     'comments',comments,...
                     'addedby',addedby,...
                     'addeddate',datestr(now,31),...
                     'info','npc_adddata');
fprintf('added dataset %s datasetid %d\n',dataname,dsid);

for ii=1:length(celldata),
   valrespfile=sprintf('../val_data/%s_val.mat',celldata(ii).cellid);
   
   [add,dfid]=sqlinsert('nDataFile',...
                        'cellid',celldata(ii).cellid,...
                        'datasetid',dsid,...
                        'area',area,...
                        'system',system,...
                        'path',datapath,...
                        'respfile',celldata(ii).datafile,...
                        'stimfile',celldata(ii).datafile,...
                        'valrespfile',valrespfile,...
                        'valstimfile',celldata(ii).datafile,...
                        'comments','',...
                        'binsize',binsize,...
                        'stimHz',stimHz,...
                        'respHz',respHz,...
                        'addedby',addedby,...
                        'addeddate',datestr(now,31),...
                        'info','npc_adddata2');
   fprintf('added cell %s datafileid %d\n',celldata(ii).cellid,dfid);
end

filename='fieldL_data.tgz';
comment='Field L conspecific birdsong data';
[add,fileid]=sqlinsert('nFiles',...
                       'datasetid',dsid,...
                       'path',datapath,...
                       'filename',filename,...
                       'comment',comment,...
                       'contenttype','application/octet-stream',...
                       'category','dataset',...
                       'seclevel',2,...
                       'addedby',addedby,...
                       'addeddate',datestr(now,31),...
                       'info','npc_adddata');
fprintf('added file %s id %d\n',filename,fileid);

filename='README';
comment=['Field L conspecific birdsong data general information'];
[add,fileid]=sqlinsert('nFiles',...
                       'datasetid',dsid,...
                       'path',datapath,...
                       'filename',filename,...
                       'contenttype','text/plain',...
                       'comment',comment,...
                       'category','dataset',...
                       'seclevel',2,...
                       'addedby',addedby,...
                       'addeddate',datestr(now,31),...
                       'info','npc_adddata');
fprintf('added file %s id %d\n',filename,fileid);
 
