

dbopen('polka','david','nine1997','music');

spokendata=mysql(['select distinct songid from dGenre where genre in' ...
            ' ("Audio Book","Book","Spoken Word")']);

for ii=1:length(spokendata),
   sql=['UPDATE dMusic set skiprand=1 where id=',...
        num2str(spokendata(ii).songid)];
   mysql(sql);
   
end
sql=['UPDATE dMusic set skiprand=1 where filemissing'];
mysql(sql);

% clean up some genres
greplace={{'Other',''},...
          {'Unknown Genre',''},...
          {'<Unknown>',''},...
          {'Unsorted',''},...
          {'sing',''},...
          {'default',''},...
          {'genre',''},...
          {'Misc',''},...
          {'.',''},...
          {'Miscellaneous',''},...
          {'Music',''},...
          {'not supported',''},...
          {'Typical movie music','Soundtrack'},...
          {'Acoustic Punk','Acoustic','Punk'},...
          {'Acoustic Rock','Acoustic'},...
          {'Alt. Rock','Alternative','Rock'},...
          {'Alternative-Rock','Alternative','Rock'},...
          {'Alternative and Punk','Alternative','Punk'},...
          {'Alternative Metal','Alternative','Metal'},...
          {'Alternative Rock','Alternative','Rock'},...
          {'Alternative/Indie','Alternative'},...
          {'AlternRock Alt. Rock','Alternative','Rock'},...
          {'Alt-Folk','Alternative','Folk'},...
          {'Alternative & Punk','Acoustic','Punk'},...
          {'Ballads','Ballad'},...
          {'Beatles','Rock'},...
          {'Big Beats','Big Beat'},...
          {'Blues rock','Blues','Rock'},...
          {'Brit Bands','BritPop'},...
          {'Brit Pop','BritPop'},...
          {'Book','Audio Book','Spoken Word'},...
          {'Children''s Music','Children''s'},...
          {'Children''s storytime','Children''s'},...
          {'ChristianAlternative','Christian Alternative'},...
          {'Comedy/Rock','Comedy','Rock'},...
          {'Country Rock','Country','Rock'},...
          {'Classic Rock Covers','Classic Rock','Cover'},...
          {'Classical (32) Classical','Classical'},...
          {'Club','Club/Dance'},...
          {'Club Dance','Club/Dance'},...
          {'Dance & DJ','Dance'},...
          {'Dance Hall','Dancehall'},...
          {'Drum ''n Bass','Drum & Bass'},...
          {'Electro','Electronic'},...
          {'Electro-Pop','Electropop'},...
          {'Elektro Pop','Electropop'},...
          {'Electronic | Astralwerks','Electronic'},...
          {'Electronica','Electronic'},...
          {'Electronica & Dance','Electronic','Dance'},...
          {'Electronica/Dance','Electronic','Dance'},...
          {'Ethereal','Ambient'},...
          {'Eurodance','Euro-Techno'},...
          {'Film Soundtrack','Soundtrack'},...
          {'Folk-Rock','Folk/Rock'},...
          {'Folk Rock','Folk/Rock'},...
          {'Folk-Rock Folk/Rock','Folk','Rock'},...
          {'Folky Shit','Folk'},...
          {'Game','Video Game'},...
          {'General Alternative','Alternative'},...
          {'General Blues','Blues'},...
          {'General Classical','Classical'},...
          {'General Folk','Folk'},...
          {'General Punk','Punk'},...
          {'General Rock','Rock'},...
          {'General R&B','R&B'},...
          {'General Soundtrack','Soundtrack'},...
          {'Gospel & Religious','Gospel'},...
          {'Gothic Rock','Gothic'},...
          {'Hard Rock & Metal','Hard Rock','Metal'},...
          {'Hip-Hop','Hip Hop'},...
          {'Hip-Hop - Underground','Hip Hop','Indie'},...
          {'Hip-Hop/Rap','Hip Hop','Rap'},...
          {'Hip Hop/Rap','Hip Hop','Rap'},...
          {'Hip-Hop / Rap','Hip Hop','Rap'},...
          {'Hip Hop / Rap','Hip Hop','Rap'},...
          {'HipHop','Hip Hop'},...
          {'Humor','Comedy'},...
          {'Indie Rock','Indie'},...
          {'Jam Bands','Jam Band'},...
          {'Jazz Rock','Jazz','Rock'},...
          {'Jazz Vocals','Jazz Vocal'},...
          {'Jazz - Hard Bop','Jazz','Hard Bop'},...
          {'Jazz+Funk','Jazz','Funk'},...
          {'Lo-Fi/Garage','Lo-Fi','Garage'},...
          {'Mash-up','Mashup'},...
          {'Miscellaneous Classical','Classical'},...
          {'ModRock','Modern Rock'},...
          {'oldschool','Old School'},...
          {'Persia','Persian'},...
          {'Pop-Folk','Pop','Folk'},...
          {'Pop-Punk','Pop Punk'},...
          {'Pop / Punk Rock','Pop','Rock','Punk'},...
          {'Pop/Funk','Pop','Funk'},...
          {'Pop/Rock','Rock'},...
          {'PopRock','Rock','Pop'},...
          {'Post Punk','Post-Punk'},...
          {'Post Rock','Post-Rock'},...
          {'Progress. Rock','Progressive Rock'},...
          {'Prog-Rock/Art Rock','Progressive Rock','Art Rock'},...
          {'Psychadelic','Psychedelic'},...
          {'Psychadel. Rock','Psychedelic','Rock'},...
          {'Psychadelic Rock','Psychedelic','Rock'},...
          {'Punk Rock','Punk'},...
          {'Post-Rock/Experimental','Post-Rock','Experimental'},...
          {'Rap & Hip Hop','Rap','Hip Hop'},...
          {'Rap & Hip-Hop','Rap','Hip Hop'},...
          {'Rap/Hip-Hop','Rap','Hip Hop'},...
          {'Rap/R&B','Rap','R&B'},...
          {'Rock & Roll','Rock'},...
          {'R & B','R&B'},...
          {'Rock - Blues','Rock','Blues'},...
          {'Rock Pop','Rock','Pop'},...
          {'rock_pop','Rock','Pop'},...
          {'Rock/Alternative','Rock','Alternative'},...
          {'Rock/Pop','Rock','Pop'},...
          {'Rock, Pop Rock, New Wave, Electronic, Synthpop','Rock','Pop','New Wave', 'Electronic', 'Synthpop'},...
          {'Rock, Punk, Punkrock, Noise, Noiserock, Alternative, Indie, Whatever','Rock','Punk','Noise', 'Alternative', 'Indie'},...
          {'Rock / Metal / Alternative','Rock','Metal','Alternative'},...
          {'Singer/ Songwriter','Singer/Songwriter'},...
          {'Singer/songwriter','Singer/Songwriter'},...
          {'Soul And R&B','Soul','R&B'},...
          {'Sound Track','Soundtrack'},...
          {'Soundtracks','Soundtrack'},...
          {'Synth-Pop','Synthpop'},...
          {'Symphony','Classical'},...
          {'Trip Hop','Trip-Hop'},...
          {'Top 40','Pop'},...
          {'Unclassifiable',''},...
          {'Unknown',''},...
          {'2006 - 2010',''}};
for gg=1:length(greplace),
   for ii=3:length(greplace{gg}),
      sql=['INSERT INTO dGenre (songid,genre,user,private)',...
           ' SELECT songid,"',greplace{gg}{ii},'",user,private',...
           ' FROM dGenre WHERE genre="',greplace{gg}{1},'"'];
      [res,cc]=mysql(sql);
      fprintf('(%d) %s -> %s\n',cc,greplace{gg}{1},greplace{gg}{ii});
   end
   
   sql=['UPDATE dGenre set genre="',greplace{gg}{2},'"',...
        ' WHERE genre="',greplace{gg}{1},'"'];
   mysql(sql);
   
   sql=['UPDATE dMusic set genre="',greplace{gg}{2},'"',...
        ' WHERE genre="',greplace{gg}{1},'"'];
   [res,cc]=mysql(sql);
   fprintf('(%d) %s -> %s\n',cc,greplace{gg}{1},greplace{gg}{2});
   
end

genrefactor=0.5;
sourcefactor=0.4;
artistfactor=0.125;

% extra tweaks for unrated songs:
genrefactor2=0.5;
sourcefactor2=0.5;

% adjusting with genre averages
sql=['SELECT count(dGenre.songid) as gcount,genre,',...
     'avg(b1) as e1,avg(b2) as e2,avg(b3) as e3,',...
     'avg(b4) as e4,avg(b5) as e5,avg(b6) as e6',...
     ' FROM dEigProj,dGenre',...
     ' WHERE dEigProj.songid=dGenre.songid AND b1<>0 GROUP BY genre'];
genredata=mysql(sql);
ee=[cat(1,genredata.e1) cat(1,genredata.e2) cat(1,genredata.e3),...
    cat(1,genredata.e4) cat(1,genredata.e5) cat(1,genredata.e6)];

for gg=1:length(genredata),
   if sum(abs(ee(gg,:)))>0,

      sql=sprintf(['UPDATE dEigProj,dGenre SET',...
                   ' dEigProj.e1=dEigProj.b1+%.5f,',...
                   ' dEigProj.e2=dEigProj.b2+%.5f,',...
                   ' dEigProj.e3=dEigProj.b3+%.5f,',...
                   ' dEigProj.e4=dEigProj.b4+%.5f,',...
                   ' dEigProj.e5=dEigProj.b5+%.5f,',...
                   ' dEigProj.e6=dEigProj.b6+%.5f',...
                   ' WHERE dEigProj.songid=dGenre.songid',...
                   ' AND dGenre.genre="%s"'],...
                  ee(gg,:).*genrefactor,genredata(gg).genre);
      mysql(sql);
      
      % inch up un-rated songs a bit more
      sql=sprintf(['UPDATE dEigProj,dGenre SET',...
                   ' dEigProj.e1=dEigProj.e1+%.5f,',...
                   ' dEigProj.e2=dEigProj.e2+%.5f,',...
                   ' dEigProj.e3=dEigProj.e3+%.5f,',...
                   ' dEigProj.e4=dEigProj.e4+%.5f,',...
                   ' dEigProj.e5=dEigProj.e5+%.5f,',...
                   ' dEigProj.e6=dEigProj.e6+%.5f',...
                   ' WHERE dEigProj.songid=dGenre.songid',...
                   ' AND dGenre.genre="%s"',...
                   ' AND dEigProj.b1=0'],...
                  ee(gg,:).*genrefactor2,genredata(gg).genre);
      mysql(sql);
   end
   fprintf('%s (%d) %5.3f %5.3f %5.3f %5.3f %5.3f %5.3f\n',...
           genredata(gg).genre,genredata(gg).gcount,ee(gg,:));
   
end

% adjusting with source averages
disp('including dups in source adjustment');
sql=['SELECT count(dMusic.id) as gcount,source,',...
     'sum(b1) as e1,sum(b2) as e2,sum(b3) as e3,',...
     'sum(b4) as e4,sum(b5) as e5,sum(b6) as e6',...
     ' FROM dEigProj, dMusic',...
     ' WHERE dEigProj.songid=dMusic.id',...
     ' AND b1<>0',...
     ' AND not(isnull(source)) AND source<>""',...
     ' GROUP BY source'];
sdata=mysql(sql);
sql=['SELECT count(dMusic.id) as gcount,source,',...
     'sum(b1) as e1,sum(b2) as e2,sum(b3) as e3,',...
     'sum(b4) as e4,sum(b5) as e5,sum(b6) as e6',...
     ' FROM dEigProj, dMusic',...
     ' WHERE dEigProj.songid=dMusic.dup',...
     ' AND b1<>0',...
     ' AND not(isnull(source)) AND source<>""',...
     ' GROUP BY source'];
ddata=mysql(sql);
sources={sdata.source};
dsources={ddata.source};

ee=zeros(length(sources),6);
for eei=1:length(sources),
   ddi=find(strcmp(sources{eei},dsources));
   if ~isempty(ddi),
      ee(eei,:)=([sdata(eei).e1 sdata(eei).e2 sdata(eei).e3 ...
                  sdata(eei).e4 sdata(eei).e5 sdata(eei).e6]+...
                 [ddata(ddi).e1 ddata(ddi).e2 ddata(ddi).e3 ...
                  ddata(ddi).e4 ddata(ddi).e5 ddata(ddi).e6])./...
                (sdata(eei).gcount+ddata(ddi).gcount);
   else
      ee(eei,:)=([sdata(eei).e1 sdata(eei).e2 sdata(eei).e3 ...
                  sdata(eei).e4 sdata(eei).e5 sdata(eei).e6])./...
                (sdata(eei).gcount);
   end
end

for gg=1:length(sdata),
   if sum(abs(ee(gg,:)))>0,

      % update 
      sql=sprintf(['UPDATE dEigProj,dMusic SET',...
                   ' dEigProj.e1=dEigProj.e1+%.5f,',...
                   ' dEigProj.e2=dEigProj.e2+%.5f,',...
                   ' dEigProj.e3=dEigProj.e3+%.5f,',...
                   ' dEigProj.e4=dEigProj.e4+%.5f,',...
                   ' dEigProj.e5=dEigProj.e5+%.5f,',...
                   ' dEigProj.e6=dEigProj.e6+%.5f',...
                   ' WHERE (dEigProj.songid=dMusic.id OR dEigProj.songid=dMusic.dup)',...
                   ' AND dMusic.source="%s"'],...
                  ee(gg,:).*sourcefactor,sdata(gg).source);
      
      mysql(sql);
      
      sql=['SELECT dEigProj.songid,dMusic.source,dMusic.id,dMusic.dup',...
           ' FROM dMusic,dEigProj',...
           ' WHERE dMusic.source="',sdata(gg).source,'"',...
           ' AND dMusic.dup=dEigProj.songid'];
      
      % inch up un-rated songs a bit more
      sql=sprintf(['UPDATE dEigProj,dMusic SET',...
                   ' dEigProj.e1=dEigProj.e1+%.5f,',...
                   ' dEigProj.e2=dEigProj.e2+%.5f,',...
                   ' dEigProj.e3=dEigProj.e3+%.5f,',...
                   ' dEigProj.e4=dEigProj.e4+%.5f,',...
                   ' dEigProj.e5=dEigProj.e5+%.5f,',...
                   ' dEigProj.e6=dEigProj.e6+%.5f',...
                   ' WHERE (dEigProj.songid=dMusic.id OR dEigProj.songid=dMusic.dup)',...
                   ' AND dMusic.source="%s"',...
                   ' AND dEigProj.b1=0'],...
                  ee(gg,:).*sourcefactor2,sdata(gg).source);
                
      mysql(sql);
   end
   fprintf('%s (%d) %5.3f %5.3f %5.3f %5.3f %5.3f %5.3f\n',...
           sdata(gg).source,sdata(gg).gcount,ee(gg,:));
   
end

% adjusting with artist averages
sql=['SELECT count(dMusic.id) as gcount,artist,',...
     'avg(b1) as e1,avg(b2) as e2,avg(b3) as e3,',...
     'avg(b4) as e4,avg(b5) as e5,avg(b6) as e6',...
     ' FROM dEigProj,dMusic',...
     ' WHERE dEigProj.songid=dMusic.id',...
     ' AND b1<>0',...
     ' AND not(dup or filemissing)',...
     ' AND not(isnull(artist)) AND artist<>""',...
     ' GROUP BY artist'];
sdata=mysql(sql);
ee=[cat(1,sdata.e1) cat(1,sdata.e2) cat(1,sdata.e3),...
    cat(1,sdata.e4) cat(1,sdata.e5) cat(1,sdata.e6)];

for gg=1:length(sdata),
   if sum(abs(ee(gg,:)))>0,

      sql=sprintf(['UPDATE dEigProj,dMusic SET',...
                   ' dEigProj.e1=dEigProj.e1+%.5f,',...
                   ' dEigProj.e2=dEigProj.e2+%.5f,',...
                   ' dEigProj.e3=dEigProj.e3+%.5f,',...
                   ' dEigProj.e4=dEigProj.e4+%.5f,',...
                   ' dEigProj.e5=dEigProj.e5+%.5f,',...
                   ' dEigProj.e6=dEigProj.e6+%.5f',...
                   ' WHERE dEigProj.songid=dMusic.id',...
                   ' AND dMusic.artist="%s"'],...
                  ee(gg,:).*artistfactor,sdata(gg).artist);
      try
         mysql(sql);
      catch
         disp('error on this one...');
      end
   end
   fprintf('%s (%d) %5.3f %5.3f %5.3f %5.3f %5.3f %5.3f\n',...
           sdata(gg).artist,sdata(gg).gcount,ee(gg,:));
   
end
