
dbopen;

sql=['SELECT * FROM dMusic WHERE id3bad AND not(isnull(artist)) AND' ...
     ' artist<>""'];
songdata=mysql(sql);

for ii=1:length(songdata),
   
   [w, s]=unix(['id3v2 -l "',songdata(ii).file,'"']);
   
   ii
   ff=findstr(s,'No ID3 tag');
   if ~isempty(ff),
      %songdata(ii)
      ts=['sudo env LD_LIBRARY_PATH=/usr/local/lib id3v2 -a "',...
            songdata(ii).artist,'"',...
            ' -A "',songdata(ii).album,'"',...
            ' -t "',songdata(ii).title,'"',...
            ' -c "',songdata(ii).comment,'"',...
            ' -T "',num2str(songdata(ii).track),'"',...
            ' --TLEN "',num2str(songdata(ii).playsec),'000"',...
            ' --TCON "',songdata(ii).genre,'"',...
            ' "',songdata(ii).file,'"']
      
      unix(['sudo env LD_LIBRARY_PATH=/usr/local/lib id3v2 -a "',...
            songdata(ii).artist,'"',...
            ' -A "',songdata(ii).album,'"',...
            ' -t "',songdata(ii).title,'"',...
            ' -c "',songdata(ii).comment,'"',...
            ' -T "',num2str(songdata(ii).track),'"',...
            ' --TLEN "',num2str(songdata(ii).playsec),'000"',...
            ' --TCON "',songdata(ii).genre,'"',...
            ' "',songdata(ii).file,'"']);
   else
      %s
   end
   
end






