* Discoveries of the Week:
  1) Performance results of 2 minutes of boosting during batch 240:
     - Relative stepsize boosting may not be as good as absolute stepsize (more to come on this next week)
     - Growing the stepsize dynamically helps some and hurts others
     - It's hard to do accurate timing metrics when each computer is a different speed!
  2) Normalization
     - Normalization after the compressor is much more important than normalization after the depression. 

* New Features of the week
  1) Boosting with a step size proportional to 1/variance now works.
  2) Boosting methods that use "default_fitter_loop.m" will now only calculate the minimum part of the stack needed to update it
  3) Simple per-file fitter rewritten as "boostperfile"
  4) Generalized per-file fitter which allows "across file" modules was halfway implemented but not checked in, and necessary hooks in pack/unpack_fittables were checked in. 
  5) Added a standardized the interface to boosting methods: "fit_boo.m" which may let us remove some code later.

* Questions of the week:
  1) How models with nonlinear parameters will be interpreted is beyond me; "distance" between different fits is not euclidean at all. 
  
