function enqueue_single_model(modulekeys, batch, cellid, training_set, test_set)
    s = ['fit_single_model(' repl_write(modulekeys) ...
         ', ' num2str(batch) ...     
         ', ' repl_write(cellid) ...
         ', ' repl_write(training_set) ...
         ', ' repl_write(test_set) ')'];
    fprintf('%s', s);
    dbaddqueuemaster(s)
end