% function masterid=dbcreatesite(params)
%
% created SVD 2005-11-21
%
function masterid=dbcreatesite(params)

dbopen;

sql=sprintf('SELECT * FROM gPenetration WHERE id=%d',params.penid);
pdata=mysql(sql);
if length(pdata)==0,
   error('Penetration not found in cellDB!');
end

if pdata.numchans >1,
   cellid=[params.SiteID,'-a1'];
else
   cellid=[params.SiteID,'-1'];
end

[aff,masterid]=sqlinsert('gCellMaster',...
                         'siteid',params.SiteID,...
                         'cellid',params.SiteID,...
                         'penid',params.penid,...
                         'penname',pdata.penname,...
                         'animal',pdata.animal,...
                         'well',pdata.well,...
                         'training',pdata.training,...
                         'findtime',datestr(now,'HH:MM'),...
                         'addedby',pdata.who,...
                         'info','dbcreatepen.m');
fprintf('added gCellMaster entry %d\n',masterid);

[aff,singleid]=sqlinsert('gSingleCell',...
                         'siteid',params.SiteID,...
                         'cellid',cellid,...
                         'masterid',masterid,...
                         'penid',params.penid,...
                         'channel','a',...
                         'unit',1,...
                         'channum',1,...
                         'addedby',pdata.who,...
                         'info','dbcreatepen.m');
fprintf('added gSingleCell entry %d\n',singleid);

