% function rawid=dbcreateraw(params,runclass,mfilename,evpfilename)
%
% created SVD 2005-11-21
%
function rawid=dbcreateraw(params,runclass,mfilename,evpfilename)

dbopen;

sql=sprintf('SELECT * FROM gRunClass WHERE name="%s"',runclass);
rdata=mysql(sql);
if length(rdata)==0,
   error('runclass not found in cellDB!');
end

sql=sprintf('SELECT * FROM gCellMaster WHERE id=%d',params.masterid);
sdata=mysql(sql);
if length(sdata)==0,
   error('Site not found in cellDB!');
end
sql=sprintf('SELECT * FROM gSingleCell WHERE masterid=%d',params.masterid);
celldata=mysql(sql);
if length(celldata)==0,
   error('Cell not found in cellDB!');
end

[respfile,resppath]=basename(mfilename);

% avoid losing backslashes in SQL
resppath=strrep(resppath,'\','\\');
evpfilename=strrep(evpfilename,'\','\\');

if strcmp(params.Physiology,'No'),
    behavior='active';
elseif strcmp(params.Physiology,'Yes -- Passive'),
    behavior='passive';
elseif strcmp(params.Physiology,'Yes -- Behavior'),
    behavior='active';
end

[aff,rawid]=sqlinsert('gDataRaw',...
                      'cellid',params.SiteID,...
                      'masterid',params.masterid,...
                      'runclass',runclass,...
                      'runclassid',rdata.id,...
                      'task',rdata.task,...
                      'training',sdata.training,...
                      'respfileevp',evpfilename,...
                      'respfile',respfile,...
                      'resppath',resppath,...
                      'fixtime',datestr(now,'HH:MM'),...
                      'behavior',behavior,...
                      'stimclass',rdata.stimclass,...
                      'addedby',sdata.addedby,...
                      'info','dbcreatepen.m');
fprintf('added gDataRaw entry %d\n',rawid);

[aff,singlerawid]=sqlinsert('gSingleRaw',...
                         'cellid',celldata.cellid,...
                         'masterid',params.masterid,...
                         'singleid',celldata.id,...
                         'penid',params.penid,...
                         'rawid',rawid,...
                         'channel','a',...
                         'unit',1,...
                         'channum',1,...
                         'addedby',sdata.addedby,...
                         'info','dbcreatepen.m');
fprintf('added gSingleRaw entry %d\n',singlerawid);

