% function batchfill(batchidx)
%
function batchfill(batchidx)

MINLEN=0;

if ~exist('batchidx'),
   disp('ERROR: batchidx parameter required');
   return
end

dbopen;

sql=['SELECT * FROM sBatch where id=',num2str(batchidx)];
batchdata=mysql(sql);

rcsetstrings;
if batchdata.stimspeedid==0,
   sspeed='';
else
   sspeed=speedstr{batchdata.stimspeedid+1};
end
if batchdata.attstate==0,
   satt='';
else
   satt=['/',attstr{batchdata.attstate+1}];
end
resbase=['.',runclassstr{batchdata.runclassid+1},sspeed,...
         '.',batchdata.kernfmt, ...
         '.',respfilefmtstr{batchdata.respfmtcode+1},'.res.mat'];
kernbase=['.',runclassstr{batchdata.runclassid+1},sspeed,...
          '.',batchdata.kernfmt, ...
          '.',respfilefmtstr{batchdata.respfmtcode+1},'.kern.mat'];

sql=['SELECT DISTINCT sCellFile.masterid,sCellFile.cellid,',...
     'sCellFile.path,sum(resplen) as totlen,sRunData.id',...
     ' FROM sCellFile LEFT JOIN sRunData',...
     ' ON sCellFile.masterid=sRunData.masterid',...
     ' AND sRunData.batch=',num2str(batchidx),...
     ' WHERE runclassid=',num2str(batchdata.runclassid),...
     ' AND stimspeedid=',num2str(batchdata.stimspeedid),...
     ' AND respfmtcode=',num2str(batchdata.respfmtcode),...
     ' AND stimfmtcode=',num2str(batchdata.stimfmtcode),...
     ' AND (sCellFile.cellid>"m006" OR sCellFile.cellid="m0000")',...
     ' AND sCellFile.cellid<>"R240A"',...
     ' GROUP BY sCellFile.cellid',...
     ' ORDER BY sCellFile.cellid,path'];
filedata=mysql(sql);



for ii=1:length(filedata),
   if ~isempty(filedata(ii).id),
      % skip cell already in batch
      filedata(ii).add=0;
   elseif filedata(ii).totlen>MINLEN,
      fprintf('adding cell %s (totlen=%d)\n',...
              filedata(ii).cellid,filedata(ii).totlen);
      filedata(ii).add=1;
   else
      fprintf('skipping cell %s (totlen=%d)\n',...
              filedata(ii).cellid,filedata(ii).totlen);
      filedata(ii).add=0;
   end
end

yn=input(sprintf('proceed with %d additions (y/[n])? ',...
                 sum(cat(1,filedata.add))),'s');

if strcmp(yn,'y'),
   for ii=find(cat(2,filedata.add)),
      sql=['INSERT INTO sRunData ',...
           ' (masterid,cellid,batch,respath,resfile,kernfile)',...
           ' VALUES (',num2str(filedata(ii).masterid),',',...
           '"',filedata(ii).cellid,'",',...
           num2str(batchidx),',',...
           '"',filedata(ii).path,'",',...
           '"',[filedata(ii).cellid,resbase],'",',...
           '"',[filedata(ii).cellid,kernbase],'")'];
      mysql(sql);
   end
end

